server:
  port: 9002
#  设置tnmeleaf 缓存关闭
spring:
  thymeleaf:
    cache: false

#    配置应用名称
  application:
    name: UserWebRibbo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
