server:
  port: 8888

spring:
  application:
    name: EurekaServer01
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    ervice-url:
      defaultZone: http://localhost:${server.port}/eureka
