server:
  port: 10086

spring:
  application:
    name: EurekaServer

#    register-with-eureka: false
#    fetch-registry: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka
